version: '3.8'

services:
  backend:
    image: olharyzha/tracker-backend:latest
    ports:
      - '8000:8000'

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - '8080:80'
    environment:
      - VITE_API_BASE_URL=http://backend:8000/api/
