version: '3.8'

services:
  backend:
    image: olharyzha/tracker-backend:latest
    ports:
      - '8000:8000'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 10s
      timeout: 5s
      retries: 12

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - '8080:80'
    environment:
      - VITE_API_BASE_URL=http://backend:8000/api/
