name: Frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      backend:
        image: olharyzha/tracker-backend:latest
        ports:
          - 8000:8000
        options: >-
          --health-cmd="curl --fail http://localhost:8000/health || exit 1"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Create .env.production
        run: echo "VITE_API_BASE_URL=http://backend:8000/api/" > .env.production

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run typecheck

      - name: Build
        run: npm run build

      - name: Run unit tests
        run: npm run test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Wait for backend to be healthy
        run: |
          for i in {1..20}; do
            curl http://localhost:8000/health && break
            echo "Waiting for backend..." && sleep 3
          done

      - name: Start production server
        run: npm run preview &

      - name: Run E2E tests
        run: npm run test:e2e

      - name: Upload Playwright report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
