name: Frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  VITE_API_BASE_URL: http://localhost:8000/api

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run typecheck

      - name: Run unit tests
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build frontend
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist

  e2e:
    runs-on: ubuntu-latest
    needs: build
    services:
      backend:
        image: olharyzha/tracker-backend:latest
        ports:
          - 8000:8000
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install project dependencies
        run: npm ci --legacy-peer-deps

      - name: Install Playwright Test
        run: npm install --legacy-peer-deps --no-save @playwright/test@1.53.2

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build and start frontend via Docker Compose
        run: |
          docker compose up --build -d frontend
      - name: Wait for frontend to be ready
        run: |
          for i in {1..20}; do
            if curl --fail http://localhost:8080/; then
              echo "Frontend is up!"; break;
            fi
            echo "Waiting for frontend..."; sleep 3;
          done

      - name: Run E2E tests
        run: npx playwright test --config=playwright.config.ts

      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
